// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY8IeXKOXRWRCaFb2r7D4Zzgca-d3ayqY',
    appId: '1:860766835118:web:3ee051a9e1b046eda4383f',
    messagingSenderId: '860766835118',
    projectId: 'example-push-jfq',
    authDomain: 'example-push-jfq.firebaseapp.com',
    storageBucket: 'example-push-jfq.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASAhb0uLQzqspEeOFrlb5wEnP-CCH0gck',
    appId: '1:860766835118:android:a9a9b979c4e9346ca4383f',
    messagingSenderId: '860766835118',
    projectId: 'example-push-jfq',
    storageBucket: 'example-push-jfq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaZdJtwV3gkbWFyNuQ1N5Ik04gEJtErkI',
    appId: '1:860766835118:ios:d893a19b22a09446a4383f',
    messagingSenderId: '860766835118',
    projectId: 'example-push-jfq',
    storageBucket: 'example-push-jfq.appspot.com',
    iosClientId: '860766835118-i99j6loddn03nhih04kt98hcbtj8kb5p.apps.googleusercontent.com',
    iosBundleId: 'quirino.jonas.exemploPush',
  );
}
